#!/bin/bash

# Setup Environment Variables for Any-Agent Workflow Composer
# This script creates the required .env.local file for the frontend

set -e

echo "🔧 Setting up environment variables..."

# Check if we're in the right directory
if [ ! -d "frontend" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    echo "   Current directory: $(pwd)"
    echo "   Expected: a directory containing 'frontend' folder"
    exit 1
fi

# Get backend URL from user or use default
read -p "Enter backend URL (default: http://localhost:8000): " BACKEND_URL
BACKEND_URL=${BACKEND_URL:-http://localhost:8000}

# Remove trailing slash if present
BACKEND_URL=$(echo "$BACKEND_URL" | sed 's/\/$//')

# Create the .env.local file
ENV_FILE="frontend/.env.local"
echo "📝 Creating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# Any-Agent Workflow Composer Environment Variables
# Generated by setup-env.sh on $(date)

# Required for server-side API routes (proxying Designer requests)
BACKEND_URL=$BACKEND_URL

# Required for client-side API calls
NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL

# Add your AI provider API keys below:
# OPENAI_API_KEY=your-openai-key-here
# ANTHROPIC_API_KEY=your-anthropic-key-here
EOF

echo "✅ Environment variables configured successfully!"
echo ""
echo "📋 Created variables:"
echo "   BACKEND_URL=$BACKEND_URL"
echo "   NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL"
echo ""
echo "🔑 Next steps:"
echo "   1. Add your API keys to $ENV_FILE"
echo "   2. Run: ./scripts/dev.sh"
echo ""
echo "⚠️  Important: Both BACKEND_URL and NEXT_PUBLIC_BACKEND_URL are required"
echo "   for workflows to properly reach Analytics!" 